import '../styles/style.css';
import '../styles/components/header.css';
import '../styles/components/hero.css';
import '../styles/components/discover.css';
import '../styles/components/tour.css';
import '../styles/components/sponsors.css';
import '../styles/components/faq.css';
import '../styles/components/joinus.css';
import '../styles/components/footer.css';